const actionsTypesCatalogs = {
  LOADING_SUCCESS_CATALOGS: 'LOADING_SUCCESS_CATALOGS',
  LOAD_SUCCESS_CATALOGS: 'LOAD_SUCCESS_CATALOGS',
  LOAD_FAILURE_CATALOGS: 'LOAD_FAILURE_CATALOGS',
  SOFKA_PELICULAASIGNADA: 'sofka.peliculaasignada'
}
export default actionsTypesCatalogs
